#!/usr/bin/env bash
set -euo pipefail

if grep -q '^snd_hda_scodec_max98390 ' /proc/modules && \
   grep -q '^snd_hda_scodec_max98390_i2c ' /proc/modules; then
    echo "speakers: ON"
else
    echo "speakers: OFF"
fi
